# Generated by Django 5.1.2 on 2024-10-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
        ('users', '0002_alter_teacher_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='users.teacher'),
            preserve_default=False,
        ),
    ]
