# Generated by Django 5.1.2 on 2024-11-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizz_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
    ]
