@startuml
title Diagramme de Classes pour Schoolo

class Utilisateur {
    +id: int
    +nom: String
    +email: String
    +motDePasse: String
    +planning: Planning
    +profil: Profil
}


class Profil {
    +id: int
    +photo: String
    +bio: String
}

class Eleve extends Utilisateur {
    +niveauExperience: int
}

class Professeur extends Utilisateur {
    +specialites: List<String>
}

class Parent extends Utilisateur {
    +enfants: List<Eleve>
}

class Lecon {
    +id: int
    +titre: String
    +contenu: String
    +matiere: String
    +estPublic: boolean
    +professeur: Professeur
}

class Controle {
    +id: int
    +titre: String
    +date: Date
    +resultats: List<Resultat>
    +lecon: Lecon
}

class Resultat {
    +id: int
    +note: float
    +eleve: Eleve
    +controle: Controle
}

class Planning {
    +id: int
    +taches: List<Tache>
}

class Tache {
    +id: int
    +description: String
    +dateHeure: DateTime
}
class Quizz {
    +id: int
    +title: String
    +subject: String
    +number_of_questions: int
    +is_public: boolean
}

class Question {
    +id: int
    +text: String
    +question_type: String
    +correct_answer: String
}

class Choice {
    +id: int
    +text: String
    +is_correct: boolean
}

Quizz "1" --> "*" Question : contains
Question "0..*" --> "*" Choice : has
Utilisateur  --> "1" Planning
Utilisateur  --> "1" Profil
Parent "0..*" --> "0..*" Eleve
Lecon "0..*" --> "1" Professeur
Controle "0..*" --> "1" Lecon
Resultat "0..*" --> "1" Eleve
Controle "0..*" --> "0..*" Resultat
Planning "1" --> "0..*" Tache



@enduml
