# Generated by Django 5.1.2 on 2024-10-29 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("motDePasse", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Planning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.CharField(max_length=200)),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_debut", models.DateTimeField()),
                ("date_fin", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.utilisateur",
                    ),
                ),
                ("niveauExperience", models.IntegerField(default=0)),
            ],
            bases=("users.utilisateur",),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="planning",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.planning",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="profil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="users.profil"
            ),
        ),
        migrations.AddField(
            model_name="planning",
            name="taches",
            field=models.ManyToManyField(to="users.tache"),
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.utilisateur",
                    ),
                ),
                ("enfants", models.ManyToManyField(to="users.eleve")),
            ],
            bases=("users.utilisateur",),
        ),
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.utilisateur",
                    ),
                ),
                (
                    "specialities",
                    models.ManyToManyField(blank=True, to="users.speciality"),
                ),
            ],
            bases=("users.utilisateur",),
        ),
        migrations.CreateModel(
            name="Lecon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("contenu", models.CharField(max_length=255)),
                ("matiere", models.CharField(max_length=100)),
                ("estPublic", models.BooleanField(default=False)),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.professeur",
                    ),
                ),
            ],
        ),
    ]
