# Generated by Django 5.1.2 on 2024-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_teacher'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='lessons.lesson'),
        ),
    ]
