# Generated by Django 5.1.2 on 2024-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_schedule_rename_name_task_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='end_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='realization_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_hour',
            field=models.TimeField(null=True),
        ),
    ]
