# Generated by Django 5.1.2 on 2024-11-19 12:09

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_profile_remove_task_user_task_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='media/user_photos/NoPhoto.jpg', null=True, upload_to=apps.users.models.user_directory_path),
        ),
    ]
