name: Django Backend CI/CD with Neon.tech

on:
  push:
    branches:
      - main  # Runs on every push to main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # Match your project Python version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          source venv/bin/activate
          python manage.py migrate

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          source venv/bin/activate
          pytest  # Use `python manage.py test` if not using pytest

      - name: Package Backend
        run: |
          tar -cvf backend.tar.gz .  # Package everything

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-package
          path: backend.tar.gz
