name: Git Fame Report

on:
  push:
    branches:
      - main  # Ne s'exécute que sur la branche main

jobs:
  git-fame:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Récupérer tout l'historique et toutes les branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install git-fame
        run: pip install git-fame

      - name: Generate git-fame report
        run: git-fame --format=markdown > .github/git_fame_report.md

      - name: Commit and push report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/git_fame_report.md
          git commit -m "Update Git Fame report"
          git push
        continue-on-error: true  # Ne bloque pas le workflow si aucun changement
